feat: 9.10 for bullseye
haskell/docker-haskell pull request #134
Opened 2024-07-13 17:27 UTC by develop7

2024-07-13 19:33 UTC, GrahamCampbell requested changes

2024-07-13 19:33 UTC, GrahamCampbell commented on 9.10/bullseye/Dockerfile
> +    GHC_URL="https://downloads.haskell.org/~ghc/$GHC/ghc-$GHC-$ARCH-deb10-linux.tar.xz"; \
deb11 is needed

2024-07-17 13:43 UTC, GrahamCampbell requested changes
Probably we should do bullseye-slim, too?

2024-07-18 13:43 UTC, GrahamCampbell requested changes

2024-07-18 13:43 UTC, GrahamCampbell commented on .github/workflows/debian.yml
> +            deb: 'bullseye'
slim job missing from here, too

2024-07-18 13:43 UTC, GrahamCampbell commented on .github/workflows/debian.yml
> +            deb: 'bullseye'
we need two entries

2024-07-28 18:02 UTC, develop7 commented on .github/workflows/debian.yml
> +            deb: 'bullseye'
I think there is:

```yaml
          - ghc: '9.10.1'
            ghc_minor: '9.10'
            deb: 'slim-bullseye'
          - ghc: '9.10.1'
            ghc_minor: '9.10'
            deb: 'bullseye'
```

2024-08-09 16:20 UTC, develop7 commented
Okay, I'll bite and merge, let's see how this works

2024-08-09 16:20 UTC, merged