Arm64 Support In Dockerfile
haskell/docker-haskell pull request #21
Opened 2020-05-13 10:11 UTC by odidev

Added the support for arm64 in Dockerfile.
As GHC official binaries are not yet released for arm64, I am building the GHC binaries from its source.

2020-05-21 03:54 UTC, odidev commented
Ping @psftw could you please share your thoughts on this.

2020-06-16 05:15 UTC, odidev commented
@psftw Kindly have a look on this PR

2020-06-23 14:44 UTC, psftw commented
Thanks for your work on this @odidev. Unfortunately right now I don't have the time to see this through, and merging/publishing prematurely would be a mistake. This PR only addresses 8.8, which in the past I had experimented with and ran in to usability problems (many of which may be resolved now). I'm not sure of the current 8.8/8.10 status for GHC (+ tooling/ecosystem) on ARM, but I'd like to do significant testing and research to make sure we are not releasing anything we shouldn't be. I'm pretty sure a number of caveats would need to be documented for users in any case. I'd also like to have a sustainable smoke-testing process that can integrate with (or replace) the existing github actions. It is possible to temporarily spin up an ARM server and use it as a github action runner, but this is not ideal.

2020-08-19 18:52 UTC, GrahamCampbell commented
I think this needs doing for 8.10 too?

2020-08-21 09:36 UTC, GrahamCampbell commented on 8.8/buster/Dockerfile
> +    apt-get install -y --no-install-recommends gnupg ca-certificates dirmngr curl git wget  \
don't need wget

2020-08-21 09:36 UTC, GrahamCampbell commented on 8.8/buster/Dockerfile
> +        wget https://downloads.haskell.org/~ghc/8.8.3/ghc-8.8.3-aarch64-deb9-linux.tar.xz && \
You need to verify the download just like for stack.

2020-08-24 11:33 UTC, odidev commented
Hi,

Added the support for arm64 in Dockerfile for 8.8 and 8.10
8.8.4 source for arm64 is not available so i am using 8.8.3 for arm64.
GHC official support for arm64 is only available for 8.8 stretch. I have cross compiled the 8.8 stretch source in buster and it is working.
GHC official support for arm64 is not available for 8.10 stretch. Hence I have only added the support for ghc 8.10 buster.

The stack consist of binary whereas binary of ghc is unavailable so i cannot verify the tar as these tar consists of the source for arm64.

2021-01-28 11:17 UTC, odidev commented
@GrahamCampbell 
can you please review and let me know if any changes required?

2021-01-28 12:34 UTC, GrahamCampbell commented
I think the best approach now would be to only add ARM support for GHC 9.0, and use the official builds, which will be available, and working properly. 8.x series should be left alone.

2021-01-28 12:36 UTC, GrahamCampbell commented
https://downloads.haskell.org/~ghc/8.10.3/ghc-8.10.3-aarch64-deb10-linux.tar.xz

2021-01-29 09:15 UTC, GrahamCampbell requested changes

2021-01-29 09:15 UTC, GrahamCampbell commented on 8.10/buster/Dockerfile
> +        curl -fSL https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-linux-$arch.tar.gz -o  stack.tar.gz && \
version should not be hard coded

2021-01-29 11:22 UTC, odidev commented
I have amended the changes as per the given suggestions.

Now this PR only consists of the changes for 8.10 buster, here **8.10.3** ghc version is used for arm64 development and the latest version of stack available for arm64 is **2.1.3**. So I have updated the stack version for arm64. 

Can you please review the latest commits and let me know if any further changes is required

2021-01-29 22:42 UTC, GrahamCampbell commented
Not up to me at this point. Up to one of the maintainers with write permissions.

2021-01-29 22:43 UTC, GrahamCampbell commented
Likely they will say wait till the debian builds are ready, then change the code back: https://github.com/haskell/docker-haskell/issues/31#issuecomment-751467630

2021-02-06 19:08 UTC, psftw commented
I saw there was a GHC 8.10.4 released yesterday, so I made a few tweaks to this PR and built it on an AWS Graviton system. While I was able to get it "working", there are still critical issues with releasing an aarch64 image. Without cabal-install (and ideally Stack as well) I don't think we should ship. I would rather the issues with packaging get resolved upstream instead of hacking something here. The line in your PR to install the cabal-install package brings in another set of packages including an older GHC from upstream Debian repositories which is not what we want. Similarly, including an old version of Stack because they no longer provide binaries for aarch64 is also not going to fly.

2021-09-22 21:23 UTC, hasufell commented
ghcup supports arm now and I also have an unofficial stack binary: https://downloads.haskell.org/ghcup/unofficial-bindists/stack/2.7.3/stack-2.7.3-linux-armv7 (not distributed... these were built in an attempt to migrate stack CI to GHC gitlab, which has first-class support for ARM)

See:

* https://github.com/haskell/docker-haskell/pull/47
* https://github.com/commercialhaskell/stack/issues/5619
* https://github.com/commercialhaskell/stack/issues/5610

2021-11-24 00:07 UTC, Bodigrim commented
@psftw any chance to move this forward? Arm docker images for GHC would be a great help for package maintainers.

2021-11-24 07:42 UTC, AlistairB commented
Thanks for the ping on this @Bodigrim . FYI @psftw has stepped down from maintaining this project after many years of service.

I believe the major blockers at this point are:

- stack official ARM releases. It seems that this existed for 2.7.1, but not for 2.7.3. I would be inclined to only include an official stack release.
- CI that can build the images on ARM based CPUs. Actually it seems that travis might support this https://docs.travis-ci.com/user/multi-cpu-architectures/#multi-cpu-availability.

I'll see if I can get something fully working in travis CI with stack 2.7.1 for now. If that works then perhaps we can bug the stack maintainers (or offer a hand) :)

2021-11-24 08:28 UTC, AlistairB commented
Hmm dang, seems that the haskell github org is out of travis ci credits.

![image](https://user-images.githubusercontent.com/437253/143201989-c0a4a197-0949-4a90-81e6-64269ced610f.png)

2021-11-24 19:42 UTC, Bodigrim commented
Yeah, Travis is no longer an option for OSS maintainers. I have successful experience with ARM machines provided by drone.io, see https://github.com/haskell/bytestring/blob/master/.drone.yml and https://github.com/haskell/text/blob/master/.drone.yml

Even a `cabal`-only docker image would be very helpful.

2021-11-25 05:52 UTC, AlistairB commented
Ah drone looks nice thanks I'll try that.

Yeah, ideally we get stack too, but if it is not likely to be possible anytime soon I think it can be omitted.

2021-11-25 06:02 UTC, AlistairB commented
Although, I think someone who is a haskell org admin would need to follow https://docs.drone.io/server/provider/github/ or apply the setup bytestring has to docker-haskell?

2021-11-25 13:15 UTC, hasufell commented
> Arm docker images for GHC would be a great help for package maintainers.

I've been working on [ghcup docker images](https://gitlab.haskell.org/haskell/ghcup-hs/-/merge_requests/173), which are more flexible and lightweight than `haskell/docker` and would use the GHC CI infrastructure to build. But I haven't gotten around it yet.

2021-11-25 19:39 UTC, Bodigrim commented
@AlistairB I set up drone.io for `bytestring` and `text` myself, so you should be able to do the same for `docker-haskee` as soon as you have enough rights for the repo. CC @chessai 
Alternatively you can try emulated GitHub actions environment, e. g., https://github.com/haskell/bytestring/blob/e682cf7ad44c8299aed23e649472d8ab559109d4/.github/workflows/ci.yml#L69-L90

@hasufell true, but installing everything from the scratch takes too long for a low-latency CI, which is my use case.

2021-11-25 20:55 UTC, chessai commented
> @AlistairB I set up drone.io for `bytestring` and `text` myself, so you should be able to do the same for `docker-haskell` as soon as you have enough rights for the repo. CC @chessai Alternatively you can try emulated GitHub actions environment, e. g., https://github.com/haskell/bytestring/blob/e682cf7ad44c8299aed23e649472d8ab559109d4/.github/workflows/ci.yml#L69-L90
> 
> @hasufell true, but installing everything from the scratch takes too long for a low-latency CI, which is my use case.

@Bodigrim, @AlistairB already has admin access to this repo (docker-haskell). Did you mean another repo?

2021-11-25 20:56 UTC, Bodigrim commented
Ah, good, then he should be able to set up drone.io for `docker-haskell` himself.

2021-11-25 21:58 UTC, AlistairB commented
Ah hmm, ok let me have another go. The instructions seemed to suggest it needs to be done at an org level.

2021-11-28 07:50 UTC, AlistairB commented
So I've been [playing with the emulated approach](https://github.com/haskell/docker-haskell/pull/53/). The good news I think I have a good pattern now to make the Dockerfiles processor architecture agnostic in that PR. Unfortunately the emulated approach is not working as `uname -m` apparently returns [the processor architecture of the real host on the CI agent](https://github.com/uraimo/run-on-arch-action/issues/21), not that of the emulated ARM64 docker container.

@Bodigrim Re drone, am I correct in thinking I would need to run 'servers' and/or 'runners' myself somewhere? The instructions ask me to set up a GitHub OAuth App.

![image](https://user-images.githubusercontent.com/437253/143734046-557fa2dd-9365-4352-ad03-321d3271969e.png)

And I would need to host some `http://drone.myserver/login` or something?

I don't really want to host anything myself (if I am understanding this all correctly) and if I did I would probably set up a self hosted github CI agent.

I think if there are no viable non-self hosted options, it is actually not the worst to just have no CI verifying ARM in this repo. As when new releases are PRed against https://github.com/docker-library/official-images as part of the release process their CI should check everything.

2021-11-28 12:56 UTC, Bodigrim commented
@AlistairB Drone provides both servers and runners. I remember that GitHub integration was not documented well, but I managed to setup it for bytestring and text - just do not remember how :) 

Dunno, try adding .drone.yml to a fork first and see whether you can integrate it?

2021-11-28 18:58 UTC, AlistairB commented
Ok thanks that is good to know. I will figure this out! 😅

2021-12-05 03:48 UTC, AlistairB commented
Just an update:

- So it turns out there is a manual approval process for cloud.drone.io. I am waiting for this, then I think I am good to test the updated images on ARM.
- I have pinged the stack people on the HF slack about [2.7.3 missing aarch64 binaries](https://github.com/commercialhaskell/stack/issues/5610) and whether stack intends to produce aarch64 binaries in the future. I'd like to at least get a response from the stack people before releasing something with stack 2.7.1 (which I think is my current preference). Another option is unofficial stack binaries, but I really think the official images should not include anything unofficial.

2021-12-27 00:01 UTC, AlistairB commented
- Still waiting for drone.io account.. Another option is try to use haskell gitlab ci, like haskell language server, but that looks really complex to set up so would rather avoid.
- I pinged the stack people and someone put their hand up to automate and add 2.7.3 ARM64 binaries. However, I have investigated and it seem the official images people are happy to have old versions of binaries when newer versions have issues. I am happy to release with 2.7.1 (at least while I see no actual movement to on the 2.7.3 issue) and https://github.com/haskell/docker-haskell/pull/53 has this fallback logic.
- https://github.com/haskell/docker-haskell/pull/53 is ready to go minus CI testing ARM64 on drone.io . Feedback welcome.

2021-12-27 02:41 UTC, closed without merging